export const STUDENT_FORM_LEVELS = [
  "Peralihan",
  "Form 1",
  "Form 2",
  "Form 3",
  "Form 4",
  "Form 5",
  "Form 6 (Lower Six)",
  "Form 6 (Upper Six)",
  "Matriculation / Foundation",
  "Diploma",
];

export const MALAYSIA_SCHOOLS = [
  "Kolej Sultan Abdul Hamid",
  "Kolej Tunku Kurshiah",
  "Maktab Mahmud Alor Setar",
  "MRSM Tun Ghazali Shafie",
  "MRSM Transkrian",
  "MRSM Tun Abdul Razak",
  "SMAP Kajang",
  "SMA Persekutuan Labu",
  "SMA Sains Kuala Selangor",
  "SMJK Keat Hwa",
  "SMJK Katholik",
  "SMJK Chung Ling",
  "SMJK Jit Sin",
  "SMJK Yu Hua",
  "SM Sains Batu Pahat",
  "SM Sains Dungun",
  "SM Sains Hulu Selangor",
  "SM Sains Kuala Terengganu",
  "SM Sains Kuching",
  "SM Sains Lahad Datu",
  "SM Sains Machang",
  "SM Sains Muar",
  "SM Sains Raja Tun Uda",
  "SM Sains Rembau",
  "SM Sains Sabah",
  "SM Sains Sembrong",
  "SM Sains Seremban",
  "SM Sains Tapah",
  "SM Sains Teluk Intan",
  "SM Sains Tun Syed Sheh Barakbah",
  "SM Sains Tuanku Aishah Rohani",
  "SM Sains Tuanku Munawir",
  "SM Sains Tun Fatimah",
  "SM Sains Tuanku Muhammad",
  "SMK Abdul Rahman Talib",
  "SMK Aminuddin Baki",
  "SMK Bandar Puteri Jaya",
  "SMK Bandar Tun Hussein Onn 2",
  "SMK Bukit Bintang",
  "SMK Bukit Jalil",
  "SMK Bandar Puchong Jaya (A)",
  "SMK Chanis",
  "SMK Cheras",
  "SMK Clifford",
  "SMK Convent Kajang",
  "SMK Cochrane",
  "SMK Damansara Utama",
  "SMK Darul Ehsan",
  "SMK Desa Tun Hussein Onn",
  "SMK Dato' Ahmad Razali",
  "SMK Datuk Abdul Rahman Yaakub",
  "SMK Datuk Onn",
  "SMK Gelang Patah",
  "SMK Green Road",
  "SMK Guar Perahu",
  "SMK Hamid Khan",
  "SMK Ibrahim",
  "SMK Infant Jesus Convent Johor Bahru",
  "SMK Ismail Petra",
  "SMK Jalan Reko",
  "SMK Jalan Kebun",
  "SMK Jelutong",
  "SMK Johor Jaya 2",
  "SMK Kamil",
  "SMK Kampong Jawa",
  "SMK Kepong Baru",
  "SMK Keramat Wangsa",
  "SMK King George V",
  "SMK Kota Kemuning",
  "SMK Kota Puteri",
  "SMK Kuala Kubu Bharu",
  "SMK Kuala Lipis",
  "SMK Kubang Pasu",
  "SMK Kulim",
  "SMK Likas",
  "SMK La Salle Petaling Jaya",
  "SMK La Salle Klang",
  "SMK Lepar Hilir",
  "SMK Lok Yuk",
  "SMK Luak",
  "SMK Mahmud",
  "SMK Maxwell",
  "SMK Methodist (ACS) Klang",
  "SMK Methodist (ACS) Sitiawan",
  "SMK Mutiara Rini",
  "SMK Miri",
  "SMK Muadzam Shah",
  "SMK Munshi Abdullah",
  "SMK Pandan Mewah",
  "SMK Penang Free School",
  "SMK Perempuan Methodist Klang",
  "SMK Perempuan Pulau Pinang",
  "SMK Perempuan Sri Aman",
  "SMK Pokok Sena",
  "SMK Presint 9(2) Putrajaya",
  "SMK Putrajaya Presint 8(1)",
  "SMK Raja Muda Musa",
  "SMK Raja Chulan",
  "SMK Raja Perempuan",
  "SMK Raja Tun Azlan Shah",
  "SMK Rawang",
  "SMK Riam",
  "SMK Sacred Heart",
  "SMK Saint Columba",
  "SMK Sam Tet",
  "SMK Sandakan",
  "SMK Saujana Utama",
  "SMK Seksyen 4 Kota Damansara",
  "SMK Sains Alam Shah",
  "SMK Sains Bagan Datuk",
  "SMK Sains Banting",
  "SMK Sains Johor",
  "SMK Sains Kuching Utara",
  "SMK Sains Miri",
  "SMK Sains Muzaffar Syah",
  "SMK Sains Selangor",
  "SMK Sains Sultan Haji Ahmad Shah",
  "SMK Sains Tengku Abdullah",
  "SMK Sains Tuanku Jaafar",
  "SMK Sains Tun Syed Putra",
  "SMK Sains Tun Abdul Razak",
  "SMK Sains Tuanku Abdul Rahman",
  "SMK Selayang Bharu",
  "SMK Setia Alam",
  "SMK Setapak",
  "SMK Shah Alam",
  "SMK Shah Alam 2",
  "SMK Simpang Ampat",
  "SMK St. Anne",
  "SMK Seri Bintang Selatan",
  "SMK Seri Bandar",
  "SMK Seri Hartamas",
  "SMK Seri Kembangan",
  "SMK Seri Kota",
  "SMK Seri Mutiara",
  "SMK Seri Puteri",
  "SMK Seafield",
  "SMK Segambut",
  "SMK Seberang Jaya",
  "SMK Senai",
  "SMK Shahbandaraya",
  "SMK Sri Aman",
  "SMK Sri Permata",
  "SMK Sri Tebrau",
  "SMK Sultan Abu Bakar",
  "SMK Sultan Abdul Aziz",
  "SMK St. Mary",
  "SMK St. Michael",
  "SMK St. Paul",
  "SMK Subang Utama",
  "SMK Sungai Besi",
  "SMK Sungai Pusu",
  "SMK Syed Hassan",
  "SMK Sultan Abdul Samad",
  "SMK Sultan Ahmad Shah",
  "SMK Sultan Alam Shah",
  "SMK Sultan Alauddin",
  "SMK Sultan Badlishah",
  "SMK Sultanah Asma",
  "SMK Sultanah Bahiyah",
  "SMK Sultan Ismail",
  "SMK Sultan Ismail 2",
  "SMK Sultan Mansor Shah",
  "SMK Sultan Omar",
  "SMK Sultan Salahuddin Abdul Aziz Shah",
  "SMK Sultan Sulaiman",
  "SMK Taman Bukit Maluri",
  "SMK Taman Connaught",
  "SMK Taman Desa",
  "SMK Taman Ehsan",
  "SMK Taman Kosas",
  "SMK Taman Melati",
  "SMK Taman Perling",
  "SMK Taman Ria",
  "SMK Taman SEA",
  "SMK Taman Universiti",
  "SMK Tengku Ampuan Rahimah",
  "SMK Tengku Panglima Raja",
  "SMK Tengku Temenggong Ahmad",
  "SMK Tinggi Klang",
  "SMK Tinggi Perempuan Melaka",
  "SMK Tun Dr Ismail",
  "SMK Tun Fatimah Hashim",
  "SMK Tun Hussein Onn",
  "SMK Tunku Abdul Rahman",
  "SMK Tunku Abdul Rahman Putra",
  "SMK Tuanku Abdul Rahman",
  "SMK Tuanku Jaafar",
  "SMK USJ 13",
  "SMK USJ 4",
  "SMK Victoria",
  "SMK Vivekananda",
  "SMK Wangsa Maju Seksyen 2",
  "SMK Yusof Ishak",
  "Sekolah Berasrama Penuh Integrasi Gombak",
  "Sekolah Berasrama Penuh Integrasi Jempol",
  "Sekolah Berasrama Penuh Integrasi Kuantan",
  "Sekolah Berasrama Penuh Integrasi Rawang",
  "Sekolah Berasrama Penuh Integrasi Sabak Bernam",
  "Sekolah Menengah Agama Persekutuan Kajang",
  "Sekolah Menengah Agama Persekutuan Labu",
  "Sekolah Menengah Kebangsaan Agama Al-Irshad",
  "Sekolah Menengah Kebangsaan Agama Johor Bahru",
  "Sekolah Menengah Kebangsaan Agama Naim Lilbanat",
  "Sekolah Dato' Abdul Razak",
  "Sekolah Menengah Kebangsaan Agama Putrajaya",
  "Sekolah Menengah Kebangsaan Agama Sheikh Haji Mohd Said",
  "Sekolah Menengah Kebangsaan Infant Jesus Convent",
  "Sekolah Menengah Kebangsaan Katholik",
  "Sekolah Menengah Kebangsaan Taman SEA",
  "Sekolah Menengah Sains Johor",
  "Sekolah Menengah Sains Kota Tinggi",
  "Sekolah Menengah Sains Muzaffar Syah",
  "Sekolah Menengah Sains Tuanku Syed Putra",
  "Sekolah Seri Puteri Cyberjaya",
  "St. John's Institution",
  "Victoria Institution",
  "The Malay College Kuala Kangsar (MCKK)",
];

const STUDENT_FORM_LEVEL_SET = new Set(STUDENT_FORM_LEVELS);
const MALAYSIA_SCHOOL_SET = new Set(MALAYSIA_SCHOOLS);

export function isValidStudentFormLevel(value) {
  const v = String(value || "").trim();
  if (!v) return true;
  return STUDENT_FORM_LEVEL_SET.has(v);
}

export function isValidMalaysiaSchool(value) {
  const v = String(value || "").trim();
  if (!v) return false;
  return MALAYSIA_SCHOOL_SET.has(v);
}
